# Generated by Django 4.2.3 on 2023-07-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name': 'Завод', 'verbose_name_plural': 'Заводы'},
        ),
        migrations.AlterModelOptions(
            name='individualentrepreneur',
            options={'verbose_name': 'Индивидуальный предприниматель', 'verbose_name_plural': 'Индивидуальные предприниматели'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='retailnetwork',
            options={'verbose_name': 'Розничная сеть', 'verbose_name_plural': 'Розничные сети'},
        ),
    ]
