# Generated by Django 4.2.3 on 2023-07-11 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_contact_options_alter_factory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.RemoveField(
            model_name='factory',
            name='debt',
        ),
    ]
